version: '{build}-{branch}'
os: Windows Server 2012 R2
platform: x64
environment:
  VBOX_MSI_INSTALL_PATH: C:\VBox-4.3.12\
init:
- ps: |
   mkdir C:\downloads | Out-Null
   cd C:\downloads
   Start-FileDownload "http://download.virtualbox.org/virtualbox/4.3.12/VirtualBox-4.3.12-93733-Win.exe"
   Start-Process -FilePath "VirtualBox-4.3.12-93733-Win.exe" -ArgumentList "-silent -logging -msiparams INSTALLDIR=C:\VBox-4.3.12" -Wait
   cd $env:APPVEYOR_BUILD_FOLDER
- ps: |
   While ((Test-NetConnection google.com -Port 80 -InformationLevel Quiet) -ne "True") {
       echo "waiting for network..."
       Start-Sleep 1
   }
install:
  - set PATH=C:\VBox-4.3.12;C:\Ruby22-x64\bin;%PATH%
  - VBoxManage -v
  - ruby --version
  - gem --version
  - bundler --version
  - bundle install
build_script:
  - rake build
test_script:
  - rake acceptance[docker]
artifacts:
  - path: %APPVEYOR_BUILD_FOLDER%\target\build\repo\vagrant-workflow-tests\acceptance.log
